"""Run a GPU job on EC2 or SageMaker from anywhere with AWS API access (no SSH, no browser).

The machine is fire-and-forget: code goes up as a tarball on S3, the instance runs one job script
(``aws/jobs/<job>.sh``) under ``user-data``, streams its logs to S3 every two minutes, uploads the
job's outputs and then powers off (shutdown behaviour = terminate). A hard wall-clock cap
(``--max-hours``) powers it off even if the job hangs.

``--backend sagemaker`` runs the same job script as a SageMaker training job instead (default
``ml.g6.24xlarge``, AWS PyTorch GPU container; see ``aws/sagemaker_backend.py``): same bucket,
same outputs, same ``fetch`` destinations, with the hard cap as ``MaxRuntimeInSeconds``.

Commands::

    python aws/ec2_run.py check [--backend sagemaker]  # credentials, region, GPU quota, AMI / API + image
    python aws/ec2_run.py launch --job seg [--type g5.2xlarge] [--max-hours 12] [--env EPOCHS=40 ...]
    python aws/ec2_run.py launch --backend sagemaker --job seg [--type ml.g6.24xlarge] [--resume-from NAME]
    python aws/ec2_run.py status --job seg [--backend sagemaker]   # state + tail of the remote logs
    python aws/ec2_run.py fetch --job seg [--backend sagemaker]    # copy the job outputs into the repo
    python aws/ec2_run.py terminate --job seg [--backend sagemaker]
    python aws/ec2_run.py cleanup                     # delete bucket, roles, profile, security group

Credentials come from the environment (AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_DEFAULT_REGION).
Resources are tagged ``project=metagross`` and named ``metagross-*``.
"""

from __future__ import annotations

import argparse
import io
import json
import logging
import os
import subprocess
import sys
import tarfile
import time
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

import sagemaker_backend as smb  # aws/ is sys.path[0] when this file runs as a script

LOG = logging.getLogger("ec2_run")
REPO = Path(__file__).resolve().parents[1]
GIT_ROOT = REPO.parent if (REPO.parent / ".git").exists() else REPO
TAG = {"Key": "project", "Value": "metagross"}
ROLE = "metagross-ec2-role"
PROFILE = "metagross-ec2-profile"
SG_NAME = "metagross-no-inbound"
# Deep Learning Base OSS Nvidia Driver GPU AMI (Ubuntu 22.04): driver + CUDA preinstalled, AWS CLI present.
AMI_PARAM = "/aws/service/deeplearning/ami/x86_64/base-oss-nvidia-driver-gpu-ubuntu-22.04/latest/ami-id"
G_QUOTA_CODE = "L-DB2E81BA"  # Running On-Demand G and VT instances (vCPUs)
DEFAULT_TYPE = {"ec2": "g5.2xlarge", "sagemaker": smb.DEFAULT_INSTANCE}
VCPUS = {"g5.xlarge": 4, "g5.2xlarge": 8, "g5.4xlarge": 16, "g5.8xlarge": 32, "g6.2xlarge": 8, "g6.4xlarge": 16,
         "g4dn.2xlarge": 8, "g4dn.4xlarge": 16}

# Outputs each job uploads (globs relative to the remote repo root) and that `fetch` copies back.
JOB_OUTPUTS = {
    "seg": ["models/lraspp_offroad5_*.onnx", "models/lraspp_offroad5_*.json", "results/seg_lraspp_offroad5_*.json",
            "results/seg_teacher*.json", "deck_assets/seg_lraspp_offroad5_*.png", "runs/seg/lraspp_offroad5_*/metrics.json",
            "runs/seg/lraspp_offroad5_*/train.log", "logs/*.log", "logs/nvidia-smi.txt"],
}

USER_DATA = r"""#!/bin/bash
# metagross fire-and-forget job runner (generated by aws/ec2_run.py)
exec > >(tee -a /var/log/metagross.log) 2>&1
set -x
BUCKET="{bucket}"; JOB="{job}"; PREFIX="s3://$BUCKET/jobs/$JOB"
shutdown -h +{max_minutes}   # hard cap: power off (terminate) even if the job hangs
status() {{ echo "$(date -u +%FT%TZ) $1" | aws s3 cp - "$PREFIX/status.txt"; }}
status "booted"
HOME_DIR=/home/ubuntu; REPO_DIR=$HOME_DIR/metagross
mkdir -p $REPO_DIR && cd $REPO_DIR
aws s3 cp "s3://$BUCKET/code/metagross.tgz" /tmp/metagross.tgz && tar xzf /tmp/metagross.tgz -C $REPO_DIR
chown -R ubuntu:ubuntu $REPO_DIR
mkdir -p $REPO_DIR/logs && chown ubuntu:ubuntu $REPO_DIR/logs
( while true; do
    aws s3 sync $REPO_DIR/logs "$PREFIX/logs/" --only-show-errors
    aws s3 cp /var/log/metagross.log "$PREFIX/logs/userdata.log" --only-show-errors
    nvidia-smi --query-gpu=utilization.gpu,memory.used --format=csv,noheader > $REPO_DIR/logs/gpu_util.txt 2>/dev/null
    sleep 120
  done ) &
status "running job $JOB"
sudo -u ubuntu -H env {env} bash -lc "cd $REPO_DIR && bash aws/jobs/$JOB.sh"
RC=$?
status "job finished rc=$RC; uploading outputs"
cd $REPO_DIR
for g in {globs}; do
  for f in $g; do [ -f "$f" ] && aws s3 cp "$f" "$PREFIX/out/$f" --only-show-errors; done
done
aws s3 sync $REPO_DIR/logs "$PREFIX/logs/" --only-show-errors
aws s3 cp /var/log/metagross.log "$PREFIX/logs/userdata.log" --only-show-errors
status "DONE rc=$RC"
shutdown -h now
"""


def session():
    region = os.environ.get("AWS_DEFAULT_REGION") or os.environ.get("AWS_REGION")
    if not region:
        sys.exit("AWS_DEFAULT_REGION is not set (e.g. ap-south-1)")
    return boto3.session.Session(region_name=region)


def bucket_name(s) -> str:
    acct = s.client("sts").get_caller_identity()["Account"]
    return f"metagross-{acct}-{s.region_name}"


def identity(s) -> dict:
    ident = s.client("sts").get_caller_identity()
    return {"account": ident["Account"], "arn": ident["Arn"], "region": s.region_name}


def check(s) -> dict:
    out = identity(s)
    try:
        q = s.client("service-quotas").get_service_quota(ServiceCode="ec2", QuotaCode=G_QUOTA_CODE)
        out["g_vt_on_demand_vcpu_quota"] = q["Quota"]["Value"]
    except ClientError as exc:
        out["g_vt_on_demand_vcpu_quota"] = f"unknown ({smb.describe_denial(exc)})"
    try:
        out["ami"] = s.client("ssm").get_parameter(Name=AMI_PARAM)["Parameter"]["Value"]
    except ClientError as exc:
        out["ami"] = f"unknown ({smb.describe_denial(exc)})"
    return out


def ensure_bucket(s, name: str) -> None:
    s3 = s.client("s3")
    try:
        s3.head_bucket(Bucket=name)
        return
    except ClientError:
        pass
    kw = {} if s.region_name == "us-east-1" else {"CreateBucketConfiguration": {"LocationConstraint": s.region_name}}
    s3.create_bucket(Bucket=name, **kw)
    s3.put_public_access_block(Bucket=name, PublicAccessBlockConfiguration={
        "BlockPublicAcls": True, "IgnorePublicAcls": True, "BlockPublicPolicy": True, "RestrictPublicBuckets": True})
    LOG.info("created bucket %s", name)


def ensure_profile(s, bucket: str) -> str:
    iam = s.client("iam")
    trust = {"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Principal": {"Service": "ec2.amazonaws.com"},
                                                    "Action": "sts:AssumeRole"}]}
    try:
        iam.create_role(RoleName=ROLE, AssumeRolePolicyDocument=json.dumps(trust), Tags=[TAG])
        LOG.info("created role %s", ROLE)
    except iam.exceptions.EntityAlreadyExistsException:
        pass
    policy = {"Version": "2012-10-17", "Statement": [
        {"Effect": "Allow", "Action": ["s3:GetObject", "s3:PutObject", "s3:ListBucket"],
         "Resource": [f"arn:aws:s3:::{bucket}", f"arn:aws:s3:::{bucket}/*"]}]}
    iam.put_role_policy(RoleName=ROLE, PolicyName="metagross-bucket", PolicyDocument=json.dumps(policy))
    try:
        iam.create_instance_profile(InstanceProfileName=PROFILE, Tags=[TAG])
        iam.add_role_to_instance_profile(InstanceProfileName=PROFILE, RoleName=ROLE)
        LOG.info("created instance profile %s; waiting for IAM propagation", PROFILE)
        time.sleep(15)
    except iam.exceptions.EntityAlreadyExistsException:
        pass
    return PROFILE


def ensure_sg(s) -> str:
    ec2 = s.client("ec2")
    vpc = ec2.describe_vpcs(Filters=[{"Name": "is-default", "Values": ["true"]}])["Vpcs"][0]["VpcId"]
    got = ec2.describe_security_groups(Filters=[{"Name": "group-name", "Values": [SG_NAME]},
                                                {"Name": "vpc-id", "Values": [vpc]}])["SecurityGroups"]
    if got:
        return got[0]["GroupId"]
    sg = ec2.create_security_group(GroupName=SG_NAME, Description="metagross GPU job: no inbound, egress only",
                                   VpcId=vpc, TagSpecifications=[{"ResourceType": "security-group", "Tags": [TAG]}])
    return sg["GroupId"]


def code_tarball() -> bytes:
    """``git archive HEAD`` of the repo (committed files only: no data, venvs or run folders)."""
    rel = REPO.relative_to(GIT_ROOT).as_posix() if REPO != GIT_ROOT else ""
    tree = f"HEAD:{rel}" if rel else "HEAD"
    raw = subprocess.run(["git", "-C", str(GIT_ROOT), "archive", "--format=tar.gz", tree],
                         check=True, capture_output=True).stdout
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:gz") as tf:  # sanity: the job script must be in it
        names = tf.getnames()
    if not any(n.startswith("aws/jobs/") for n in names):
        sys.exit("aws/jobs/ is not committed: commit it first (the instance runs the committed tree)")
    return raw


def instances(s, job: str, states=("pending", "running", "stopping")) -> list[dict]:
    r = s.client("ec2").describe_instances(Filters=[
        {"Name": "tag:project", "Values": ["metagross"]}, {"Name": "tag:job", "Values": [job]},
        {"Name": "instance-state-name", "Values": list(states)}])
    return [i for res in r["Reservations"] for i in res["Instances"]]


def launch(s, job: str, itype: str, max_hours: float, env: list[str], disk_gb: int) -> str:
    if job not in JOB_OUTPUTS:
        sys.exit(f"unknown job {job!r}; known: {sorted(JOB_OUTPUTS)}")
    if instances(s, job):
        sys.exit(f"a {job} instance is already running: {[i['InstanceId'] for i in instances(s, job)]}")
    info = check(s)
    if info["ami"].startswith("unknown"):
        sys.exit(f"cannot resolve the GPU AMI: {info['ami']}")
    quota = info["g_vt_on_demand_vcpu_quota"]
    if isinstance(quota, float) and quota < VCPUS.get(itype, 0):
        sys.exit(f"G/VT on-demand vCPU quota is {quota:.0f} < {VCPUS[itype]} needed by {itype}: request an increase")
    bucket = bucket_name(s)
    ensure_bucket(s, bucket)
    s.client("s3").put_object(Bucket=bucket, Key="code/metagross.tgz", Body=code_tarball())
    s.client("s3").put_object(Bucket=bucket, Key=f"jobs/{job}/status.txt", Body=b"launching\n")
    profile = ensure_profile(s, bucket)
    sg = ensure_sg(s)
    env_s = " ".join(e for e in env if "=" in e and "'" not in e and '"' not in e)
    ud = USER_DATA.format(bucket=bucket, job=job, max_minutes=int(max_hours * 60), env=env_s,
                          globs=" ".join(JOB_OUTPUTS[job]))
    ec2 = s.client("ec2")
    for attempt in range(6):  # a fresh instance profile can take a few seconds to become usable
        try:
            r = ec2.run_instances(
                ImageId=info["ami"], InstanceType=itype, MinCount=1, MaxCount=1, UserData=ud,
                IamInstanceProfile={"Name": profile}, SecurityGroupIds=[sg],
                InstanceInitiatedShutdownBehavior="terminate",
                BlockDeviceMappings=[{"DeviceName": "/dev/sda1",
                                      "Ebs": {"VolumeSize": disk_gb, "VolumeType": "gp3", "DeleteOnTermination": True}}],
                TagSpecifications=[{"ResourceType": "instance", "Tags": [TAG, {"Key": "job", "Value": job},
                                                                         {"Key": "Name", "Value": f"metagross-{job}"}]}])
            break
        except ClientError as exc:
            if "iamInstanceProfile" in str(exc) and attempt < 5:
                time.sleep(10)
                continue
            raise
    iid = r["Instances"][0]["InstanceId"]
    LOG.info("launched %s (%s) for job %s; hard cap %.1f h; logs -> s3://%s/jobs/%s/", iid, itype, job, max_hours,
             bucket, job)
    return iid


def launch_sagemaker(s, job: str, itype: str, max_hours: float, env: list[str], volume_gb: int,
                     image: str | None, resume_from: str | None) -> str:
    """Same job as :func:`launch`, as a SageMaker training job (see ``aws/sagemaker_backend.py``)."""
    if job not in JOB_OUTPUTS:
        sys.exit(f"unknown job {job!r}; known: {sorted(JOB_OUTPUTS)}")
    try:
        sm_env = smb.validate_env(env)
        image = image or smb.image_uri(s.region_name)
        smb.ecr_repository_arn(image)
    except ValueError as exc:
        sys.exit(str(exc))
    smb.preflight(s, job)  # exits on an SCP / IAM denial or a job already in progress
    bucket = bucket_name(s)
    ensure_bucket(s, bucket)
    return smb.launch(s, job=job, bucket=bucket, tarball=code_tarball(), output_globs=JOB_OUTPUTS[job],
                      instance_type=itype, image=image, max_hours=max_hours, volume_gb=volume_gb, env=sm_env,
                      resume_from=resume_from)


def status(s, job: str, tail: int = 25) -> None:
    ins = instances(s, job, states=("pending", "running", "stopping", "stopped", "shutting-down", "terminated"))
    for i in sorted(ins, key=lambda i: i["LaunchTime"])[-3:]:
        print(f"instance {i['InstanceId']} {i['InstanceType']} {i['State']['Name']} launched {i['LaunchTime']:%Y-%m-%d %H:%M}Z")
    s3 = s.client("s3")
    bucket = bucket_name(s)
    for key in (f"jobs/{job}/status.txt",):
        try:
            print("status:", s3.get_object(Bucket=bucket, Key=key)["Body"].read().decode().strip())
        except ClientError:
            print("status: (none yet)")
    listing = s3.list_objects_v2(Bucket=bucket, Prefix=f"jobs/{job}/logs/").get("Contents", [])
    for obj in sorted(listing, key=lambda o: o["LastModified"])[-6:]:
        body = s3.get_object(Bucket=bucket, Key=obj["Key"])["Body"].read().decode(errors="replace").splitlines()
        print(f"--- {obj['Key'].split('/logs/')[-1]} ({obj['LastModified']:%H:%M}Z, {len(body)} lines)")
        for line in body[-tail:]:
            print("   ", line[:220])


def fetch(s, job: str) -> list[Path]:
    s3 = s.client("s3")
    bucket = bucket_name(s)
    prefix = f"jobs/{job}/out/"
    got: list[Path] = []
    for page in s3.get_paginator("list_objects_v2").paginate(Bucket=bucket, Prefix=prefix):
        for obj in page.get("Contents", []):
            dest = smb.output_dest(REPO, obj["Key"][len(prefix):])
            dest.parent.mkdir(parents=True, exist_ok=True)
            s3.download_file(bucket, obj["Key"], str(dest))
            got.append(dest)
    LOG.info("fetched %d files", len(got))
    for p in got:
        print(" ", p.relative_to(REPO))
    return got


def terminate(s, job: str) -> None:
    ids = [i["InstanceId"] for i in instances(s, job)]
    if ids:
        s.client("ec2").terminate_instances(InstanceIds=ids)
    LOG.info("terminated %s", ids or "nothing (no running instance)")


def cleanup(s) -> None:
    smb.cleanup(s, JOB_OUTPUTS)
    for job in JOB_OUTPUTS:
        terminate(s, job)
    iam = s.client("iam")
    try:
        iam.remove_role_from_instance_profile(InstanceProfileName=PROFILE, RoleName=ROLE)
        iam.delete_instance_profile(InstanceProfileName=PROFILE)
    except ClientError:
        pass
    try:
        iam.delete_role_policy(RoleName=ROLE, PolicyName="metagross-bucket")
        iam.delete_role(RoleName=ROLE)
    except ClientError:
        pass
    bucket = bucket_name(s)
    try:
        b = s.resource("s3").Bucket(bucket)
        b.objects.all().delete()
        b.delete()
    except ClientError:
        pass
    try:
        ec2 = s.client("ec2")
        for g in ec2.describe_security_groups(Filters=[{"Name": "group-name", "Values": [SG_NAME]}])["SecurityGroups"]:
            ec2.delete_security_group(GroupId=g["GroupId"])
    except ClientError as exc:
        LOG.warning("security group not deleted yet (%s); re-run cleanup after instances terminate", exc)
    LOG.info("cleanup done")


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    backend = argparse.ArgumentParser(add_help=False)
    backend.add_argument("--backend", choices=sorted(DEFAULT_TYPE), default="ec2")
    c = sub.add_parser("check", parents=[backend])
    c.add_argument("--type", default=None, help="sagemaker: instance type whose training quota to read")
    p = sub.add_parser("launch", parents=[backend])
    p.add_argument("--job", default="seg")
    p.add_argument("--type", default=None, help=f"default: {DEFAULT_TYPE['ec2']} (ec2), {DEFAULT_TYPE['sagemaker']} "
                                                "(sagemaker)")
    p.add_argument("--max-hours", type=float, default=12.0)
    p.add_argument("--disk-gb", type=int, default=150, help="EBS root volume (ec2) / ML storage volume (sagemaker; "
                                                             "instances with local NVMe such as ml.g6 use that instead)")
    p.add_argument("--env", nargs="*", default=[], help="KEY=VALUE passed to the job script")
    p.add_argument("--image", default=None, help="sagemaker: training image URI (default: AWS PyTorch DLC "
                                                 f"{smb.DLC_REPO}:{smb.DEFAULT_IMAGE_TAG})")
    p.add_argument("--resume-from", default=None, help="sagemaker: earlier training job whose runs/ (last.pt) the "
                                                       "new job continues from")
    for name in ("status", "fetch", "terminate"):
        q = sub.add_parser(name, parents=[backend])
        q.add_argument("--job", default="seg")
        q.add_argument("--name", default=None, help="sagemaker: training job name (default: the newest for --job)")
    sub.add_parser("cleanup")
    return ap


def main(argv: list[str] | None = None) -> None:
    a = build_parser().parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    s = session()
    sm = getattr(a, "backend", "ec2") == "sagemaker"
    if a.cmd == "check":
        info = {**identity(s), **smb.check(s, a.type or DEFAULT_TYPE["sagemaker"])} if sm else check(s)
        print(json.dumps(info, indent=1, default=str))
    elif a.cmd == "launch" and sm:
        launch_sagemaker(s, a.job, a.type or DEFAULT_TYPE["sagemaker"], a.max_hours, a.env, a.disk_gb, a.image,
                         a.resume_from)
    elif a.cmd == "launch":
        launch(s, a.job, a.type or DEFAULT_TYPE["ec2"], a.max_hours, a.env, a.disk_gb)
    elif a.cmd == "status":
        smb.status(s, a.job, a.name) if sm else status(s, a.job)
    elif a.cmd == "fetch":
        smb.fetch(s, a.job, REPO, a.name) if sm else fetch(s, a.job)
    elif a.cmd == "terminate":
        smb.stop(s, a.job, a.name) if sm else terminate(s, a.job)
    elif a.cmd == "cleanup":
        cleanup(s)


if __name__ == "__main__":
    main()
