"""Fill the metrics section of ``docs/MODEL_CARD.md`` from ``results/seg_*.json``.

Only text between ``<!-- METRICS:BEGIN -->`` and ``<!-- METRICS:END -->`` is replaced, so
every number in the card is traceable to a results file written by
``metagross.eval.seg_eval`` or ``aws/teacher_dinov2.py``; nothing is typed by hand.

    python -m metagross.train.model_card
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any, Optional

LOG = logging.getLogger("model_card")
REPO_ROOT = Path(__file__).resolve().parents[2]
BEGIN, END = "<!-- METRICS:BEGIN -->", "<!-- METRICS:END -->"
MAX_SEQ_ROWS = 6  # per split, in the false-safe-by-scene table
CLASS_ORDER = ("background/sky", "obstacle", "water/mud", "unstable (grass/dirt)", "stable (asphalt/concrete/gravel path)")


def _pct(v: Optional[float]) -> str:
    return "n/a" if v is None else f"{100 * v:.1f}"


def _ms(lat: dict[str, Any], key: str) -> str:
    v = lat.get("camera_frame", {}).get(key, {}).get("total_median_ms")
    return "n/m" if v is None else f"{v:.0f}"


def _display_name(p: Path, d: dict[str, Any]) -> str:
    """Result label, with a SMOKE marker unless the label already carries one."""
    name = d.get("label") or Path(d.get("model", {}).get("path", p.stem)).stem
    return f"SMOKE: {name}" if d.get("smoke") and "SMOKE" not in name.upper() else name


def render(results_dir: Path) -> str:
    """Markdown for all eval + teacher results found in ``results_dir``."""
    evals, teachers = [], []
    for p in sorted(results_dir.glob("seg_*.json")):
        try:
            d = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if d.get("schema") == "metagross.seg_eval/1":
            evals.append((p, d))
        elif d.get("schema") == "metagross.seg_teacher/1":
            teachers.append((p, d))
    if not evals and not teachers:
        return "_No results yet: run `metagross.eval.seg_eval` (see README)._\n"
    lines = [
        "All numbers below are generated by `python -m metagross.train.model_card` from the listed files "
        "(label **Tested** = measured on real images; SMOKE = pipeline check, not a trained model). "
        "Latency is the median wall-clock time of `Segmenter.__call__` (resize + normalise + ORT + argmax/entropy + upsample) "
        "on one 640x400 camera frame on the development laptop (4 cores / 8 threads, no GPU, CPU shared with other "
        "jobs during measurement; host details in each JSON); "
        "n/m = not measured.",
        "",
        "| Model | Eval set | n img | mIoU % | pixel acc % | false-safe % | FS obstacle % | FS water % | ms @2 thr | ms @4 thr | Source |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for p, d in evals:
        lat = d.get("latency_ms", {})
        name = _display_name(p, d)
        root = Path(next(iter(d["splits"].values()))["data_root"]).name if d["splits"] else "?"
        for sp, rep in d["splits"].items():
            o = rep["overall"]
            lines.append(
                f"| {name} | {root} {sp} | {rep['n_images']} | {_pct(o['miou'])} | {_pct(o['pixel_acc'])} | {_pct(o['false_safe_rate'])} | "
                f"{_pct(o['false_safe_obstacle'])} | {_pct(o['false_safe_water'])} | {_ms(lat, 'threads_2')} | {_ms(lat, 'threads_4')} | `{p.relative_to(REPO_ROOT).as_posix() if p.is_relative_to(REPO_ROOT) else p.name}` |"
            )
    lines += ["", "Per-class IoU (%):", "", "| Model | Eval set | " + " | ".join(CLASS_ORDER) + " |", "|---|---|" + "---|" * len(CLASS_ORDER)]
    for p, d in evals:
        name = _display_name(p, d)
        for sp, rep in d["splits"].items():
            iou = rep["overall"]["per_class_iou"]
            lines.append(f"| {name} | {sp} | " + " | ".join(_pct(iou.get(c)) for c in CLASS_ORDER) + " |")
    lines += ["", "Brightness-stratified mIoU % (images split into terciles of mean luma; dark / mid / bright):", "", "| Model | Eval set | dark | mid | bright | false-safe dark % | false-safe bright % |", "|---|---|---|---|---|---|---|"]
    for p, d in evals:
        name = _display_name(p, d)
        for sp, rep in d["splits"].items():
            b = rep.get("brightness")
            if b:
                lines.append(
                    f"| {name} | {sp} | {_pct(b['dark']['miou'])} | {_pct(b['mid']['miou'])} | {_pct(b['bright']['miou'])} | "
                    f"{_pct(b['dark']['false_safe_rate'])} | {_pct(b['bright']['false_safe_rate'])} |"
                )
    seq_rows = []
    for p, d in evals:
        name = _display_name(p, d)
        for sp, rep in d["splits"].items():
            seqs = rep.get("per_sequence") or {}
            fs_total = sum(v["false_safe_px"] for v in seqs.values())
            for sname, v in sorted(seqs.items(), key=lambda kv: -kv[1]["false_safe_px"])[:MAX_SEQ_ROWS]:
                share = v["false_safe_px"] / fs_total if fs_total else None
                seq_rows.append(f"| {name} | {sp} | {sname} | {v['n_images']} | {_pct(v['miou'])} | {_pct(v['false_safe_rate'])} | {_pct(share)} |")
    if seq_rows:
        lines += [
            "",
            f"False-safe by scene (top {MAX_SEQ_ROWS} scenes per split by false-safe pixels; last column = share of all false-safe pixels in that split):",
            "",
            "| Model | Eval set | scene | n img | mIoU % | false-safe % | share of false-safe px % |",
            "|---|---|---|---|---|---|---|",
            *seq_rows,
        ]
    if teachers:
        lines += ["", "Research reference (frozen backbone + linear head, not deployable):", "", "| Backbone | n val | mIoU % | false-safe % | Source |", "|---|---|---|---|---|"]
        for p, d in teachers:
            o = d["best_val"]["overall"]
            lines.append(f"| {d['backbone'].get('weights')} | {d['n_val']} | {_pct(o['miou'])} | {_pct(o['false_safe_rate'])} | `{p.name}` |")
    return "\n".join(lines) + "\n"


def update_card(card: Path, results_dir: Path) -> None:
    text = card.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise ValueError(f"{card} lacks {BEGIN} / {END} markers")
    body = render(results_dir)
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: f"{BEGIN}\n{body}{END}", text, flags=re.S)
    card.write_text(new, encoding="utf-8")
    LOG.info("updated %s", card)


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--card", type=Path, default=REPO_ROOT / "docs" / "MODEL_CARD.md")
    ap.add_argument("--results", type=Path, default=REPO_ROOT / "results")
    args = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    update_card(args.card, args.results)
    return 0


if __name__ == "__main__":
    sys.exit(main())
